import { type Component } from 'vue';
import {
  Bell,
  BellOff,
  Camera,
  ChartNoAxesColumnIncreasing,
  CircleOff,
  Cpu,
  DoorOpen,
  FileText,
  Globe,
  History,
  LayoutDashboard,
  Monitor,
  MonitorCog,
  Search,
  Shield,
  ShieldAlert,
  Terminal,
  UserCheck,
  Users,
  X,
} from 'lucide-vue-next';
import type { IconName } from '../types/ui';

export const iconRegistry: Record<IconName, Component> = {
  bell: Bell,
  bellOff: BellOff,
  camera: Camera,
  check: UserCheck,
  chart: ChartNoAxesColumnIncreasing,
  circleOff: CircleOff,
  close: X,
  cpu: Cpu,
  doorOpen: DoorOpen,
  file: FileText,
  globe: Globe,
  history: History,
  layout: LayoutDashboard,
  monitor: Monitor,
  monitorCog: MonitorCog,
  searchPerson: Search,
  shield: Shield,
  shieldAlert: ShieldAlert,
  terminal: Terminal,
  userCheck: UserCheck,
  users: Users,
};
